### ISSUE TITLE
Abruf Anträge bzw. Teilanträge

### ISSUE THREAD

**Issue by gharlan** [europace/baufismart-vorgaenge-api#1]
Hallo,

ich teste zurzeit die API mit den Mockdaten (https://baufismart.api.europace.de/mock), dabei ist mir Folgendes aufgefallen:

Ich rufe den Endpoint für die [Anträge eines Vorgangs](https://github.com/hypoport/vorgaenge-api/blob/cb0369351e3e90da3aa5a8e40eb517759c25f223/swagger.yaml#L193) auf, zum Beispiel `/mock/vorgaenge/885089/antraege`. Dort erhalte ich eine Liste der Anträge. Pro Antrag einen solchen Block:

```json
        {
            "antragsNummer": "890427/1",
            "datenKontext": "ECHT_GESCHAEFT",
            "zeitpunktDerAnnahme": "2015-06-02T11:58:49.531+02:00",
            "_links": {
                "self": {
                    "href": "https://baufismart.api.europace.de/mock/antraege/890427_1"
                }
            }
        }
```

Rufe ich den angegebenen Link auf, erhalte ich die Daten zum Antrag. Ich wundere mich allerdings über die URL. Laut swagger.yaml sollte es hingegen [diese URLs](https://github.com/hypoport/vorgaenge-api/blob/cb0369351e3e90da3aa5a8e40eb517759c25f223/swagger.yaml#L245-L366) geben:

`/mock/vorgaenge/{vorgangsNummer}/antraege/{antragsNummer}`
`/mock/vorgaenge/{vorgangsNummer}/antraege/{antragsNummer}/{teilantragsNummer}`
statt:
`/mock/antraege/{antragsNummer}`

Ist da die swagger.yaml eventuell nicht mehr aktuell?
Denn bei der ersten URL erhalte ich die Daten zum Vorgang statt zum Antrag, und bei der zweiten erhalte ich einen "internal server error".

Mit freundlichen Grüßen
Gregor Harlan

**Comment by gharlan** [comment]
Ich habe nun Zugriff auf Echtdaten, und dort sind die URLs so wie in der swagger.yaml angegeben.

**Comment by ptrsauer** [comment]
Ok, dass heißt die Daten des Mock sind unter Umständen nicht korrekt.

**Comment by ollio** [comment]
Gibt es hier noch Bedarf?

**Comment by caspii** [comment]
Ich weiß nicht genau, wofür mock gedacht war -- oder was es genau ist 😬 

Jedenfalls denke ich, dass mock und Echtdaten so ähnlich wie nur möglich sein sollten. Oder wir schaffen mock ab.

**Comment by ollio** [comment]
mock abschaffen klingt gut, man kann die API ja immer mit Testdaten testen

**Comment by ollio** [comment]
Mock API bei AWS gelöscht
