### ISSUE TITLE
https://baufismart.api.europace.de/v2/vorgaenge liefert max 10000 Vorgänge

### ISSUE THREAD

**Issue by Madensucher** [europace/baufismart-vorgaenge-api#12]
Wenn die Kombination aus 'page' und 'limit' die Anzahl von 10000 übersteigt, dann erhält das Ergebnis keine Vorgangsliste mehr.

" https://baufismart.api.europace.de/v2/vorgaenge/?datenKontext=ECHT_GESCHAEFT&sort=aufsteigend&page=0&limit=10000&aenderungSeit=2017-09-08T10:05:27.163Z" funktioniert, wenn aber das 'limit' auf 10001 gesetzt wird, dann nicht mehr.

**Comment by Madensucher** [comment]
Leider kann man das Problem nicht dadurch umgehen, indem man durch Angabe von 'aenderungSeit' = 'aenderungBis' die Begrenzung auf 10000 Sätze umgeht (unter der Annahme, für den angemeldeten User gibt es am Tag weniger als 10000 Änderungen): die Schnittstelle liefert keine Sätze mit einem Änderungsdatum vor dem 2018-04-06.

Damit können externe Systeme nicht mit Daten vor diesem Datum befüllt werden. Das Reporting ist hierfür auch keine Alternative, da der dortige Datenbestand nur einen eingeschränkten Satz an Informationen enthält.

**Comment by ollio** [comment]
Durch den Bugfix im Suche Service wird die Suche nun besser eingegrenzt und es werden nicht mehr mehr als 10k Vorgänge gefunden.
