### ISSUE TITLE
Patch Operation Doku ist nicht ausreichend

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgaenge-api#13]
https://htmlpreview.github.io/?https://raw.githubusercontent.com/hypoport/vorgaenge-api/master/Dokumentation/index.html#_patchoperation

**Comment by ollio** [comment]
Reicht es so: 

https://github.com/europace/baufismart-vorgaenge-api/blob/master/Dokumentation/patch.md

**Comment by caspii** [comment]
👍
