### ISSUE TITLE
https://baufismart.api.europace.de/v2/vorgaenge liefert bei einigen Kombinationen von 'anderungSeit' und 'aenderungBis' keine Vorgänge

### ISSUE THREAD

**Issue by Madensucher** [europace/baufismart-vorgaenge-api#14]
Das Problem hat scheinbar nichts mit der 10000er Grenze zu tun.

Beispiel für unerwartetes Ergebnis:
https://baufismart.api.europace.de/v2/vorgaenge/?datenKontext=ECHT_GESCHAEFT&aenderungSeit=2018-05-05T20:00:00&aenderungBis=2018-05-06T00:00:01&sort=aufsteigend&page=0&limit=5000

Im Result ist das Feld 'vorgaenge' ==  null. Erwartet wird eine Liste mit Vorgängen bzw. eine leere Liste. 

Beispiel mit erwartetem Ergebnis:
https://baufismart.api.europace.de/v2/vorgaenge/?datenKontext=ECHT_GESCHAEFT&aenderungSeit=2018-05-05T20:00:00&aenderungBis=2018-05-06T23:59:59&sort=aufsteigend&page=0&limit=5000

Auf der verwendeten Plakette werden mit dem funktionierenden Aufruf 23 Vorgänge geliefert.

**Comment by ollio** [comment]
@Madensucher tritt der Fehler noch auf?
