### ISSUE TITLE
Modernisierungsangaben fehlen

### ISSUE THREAD

**Issue by europacesupport** [europace/baufismart-vorgaenge-api#18]
Im Response sind folgende Felder erhalten
```
            "modernisierungsAngaben": {
                "wurdeModernisiert": true,
                "modernisierungsGrad": "HOCH",
                "modernisierungsJahr": 2001,
                "bodenWandTreppe": true,
                "heizungZentral": true,
                "fenster": true,
                "dach": true,
                "badWc": true,
                "stromAbwasserHeizkoerper": true,
                "waermedaemmung": true,
                "raumaufteilung": true
            },
```
Was genau fehlt noch?

**Comment by BigMichi1** [comment]
Wenn in BaufiSmart "Wurde das Objekt in der Vergangenheit modernisiert?" nein gewählt wird ist ```modernisierungsAngaben``` null, die Erwartung ist das man 
```
 "modernisierungsAngaben": {
                "wurdeModernisiert": false,
                ...
}
```
erhält 

![bildschirmfoto vom 2018-11-29 14-56-43](https://user-images.githubusercontent.com/91786/49226572-50990280-f3e7-11e8-85b5-1b4aa2e78194.png)

**Comment by ollio** [comment]
Ich würde erwarten, dass der komplette Knoten **modernisierungsAngaben** nicht mehr in der Antwort enthalten ist. Das Feld **wurdeModernisiert** ist somit eher verwirrend, da es dann ja immer true ist.
