### ISSUE TITLE
Angebot Rückdatierungsfrist fehlt in API

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgaenge-api#21]
![image](https://user-images.githubusercontent.com/3215971/49070508-1b948080-f22c-11e8-9583-343586d67097.png)

**Comment by caspii** [comment]
Warum wird das benötigt? Es können ja nur Anträge in dieser API ausgelesen werden, und im Antrag sind die Konditionen ja fest

**Comment by ollio** [comment]
An wen stellst Du diese Frage?

**Comment by caspii** [comment]
@ollio die Frage geht an C24. Sie hatten den Punkt in einem Telko erwähnt

**Comment by BigMichi1** [comment]
OK wird bei uns nicht mehr verwendet bzw. die letzten Stellen habe ich eben ausgebaut
