### ISSUE TITLE
antragsteller.weitereKontaktMoeglichkeiten now comes with truncated '\n'

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgaenge-api#22]

**Comment by caspii** [comment]
In unserem Test wird das '\n`ausgegeben. Was genau ist hier das Problem? Gerne auch Beispielfall

**Comment by BigMichi1** [comment]
Das Problem war ein Zeilenumbruch am Ende den Wir entfernt haben. Also kein Problem, sry

**Comment by caspii** [comment]
Alles klar!
