### ISSUE TITLE
Sondertilgung fehlt bei Darlehen zum Finanzierungsobjekt

### ISSUE THREAD

**Issue by BigMichi1** [europace/baufismart-vorgaenge-api#24]
Beispielfall:
RM6167

![bildschirmfoto vom 2018-11-29 17-27-10](https://user-images.githubusercontent.com/91786/49236423-6107a800-f3fc-11e8-9cf4-b68b0d744336.png)

wir erhalten in der Response für das bestehende Darlehenauf dem Finanzierungsobjekt keine Angabe über die Sondertilgung

    bestehendeDarlehen: [class BestehendesDarlehenDesFinanzierungsObjekts {
            abzuloesendeRestschuld: 1.00
            aktuelleRestschuldWennNichtAbzuloesen: null
            darlehensArt: null
            darlehensBetrag: null
            darlehensGeber: class ProduktAnbieter {
               ...
            }
            darlehensKontonummer: null
            eingetrageneGrundschuld: null
            grundschuldArt: BUCH_GRUNDSCHULD
            id: 18717583153619222
            laufzeitEnde: null
            rateMonatlich: null
            sollZins: null
            verwendenAls: ABLOESEN
            zinsBindungEndetAm: null
        }]

**Comment by ollio** [comment]
Wird auch in API Version 2.5 integriert. Leider muss dazu eine Core Erweiterung gemacht werden.
