### ISSUE TITLE
fehlende Angabe "Laufzeit bis" bei externen Bauspardarlehen

### ISSUE THREAD

**Issue by BigMichi1** [europace/baufismart-vorgaenge-api#25]
![screenshot from 2018-11-29 17-31-19](https://user-images.githubusercontent.com/91786/49236737-10dd1580-f3fd-11e8-9e3a-7bb4ea718d28.png)

wird ein externes Bauspardarlehen angegeben und die Laufzeit bis gepflegt fehlt die Angabe in der API

    nachrangigeExterneDarlehen: [class NachrangigesExternesDarlehen {
            darlehensBetrag: 15000.00
            darlehensGeber: test
            id: 21341870008214525
            rateMonatlich: 150.00
            typ: BAUSPARDARLEHEN
            zinsBindung: class ZinsBindung {
                endetAm: 2023-01-01
                jahre: null
                monate: null
                restschuldNachZinsBindungsEnde: null
            }
        }]

**Comment by ollio** [comment]
Wird in Version 2.5 gefixed
