### ISSUE TITLE
Kommentar via PATCH einem Vorgang hinzufügen

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgaenge-api#29]
Motivation: dieses Feature würde Vertrieben wie C24 helfen, ihre eigene Löschfristen fest zu bestimmen

**Comment by ollio** [comment]
Ein Kommentar am Vorgang wird nur als Ereignis geschrieben. Es gibt also als solches nicht **den Kommentar** am Vorgang. Ein Kommentar sollte also auch per PUSH über die Ereignis-API in das System kommen.

**Comment by ollio** [comment]
https://github.com/europace/baufismart-ereignisse-api/issues/7
