### ISSUE TITLE
Vorgangsdaten ändern

### ISSUE THREAD

**Issue by marcelvossmint** [europace/baufismart-vorgaenge-api#34]
Ist es möglich die zu einem Vorgang gehörenden Immobilien oder die Daten des Antragstellers über die Api zu ändern?

Laut Beispiel unterstützen die Patch-Operations nur wenige Metadaten.

**Comment by corneliaposkowski** [comment]
Ja, das ist korrekt. Die Möglichkeit Vorgangsdaten per API zu ändern ist noch in der Umsetzung. Aktuell funktioniert es nicht.
