### ISSUE TITLE
Invalid HAL Link structure at GET /v2/vorgaenge/{vorgangsNummer} response

### ISSUE THREAD

**Issue by mustafakara** [europace/baufismart-vorgaenge-api#46]
At the response of GET /v2/vorgaenge/{vorgangsNummer} call the antrage field's HAL link structure is not valid. 

For some calls to https://baufismart.api.europace.de/v2/vorgaenge/******** or https://api.europace.de/v2/vorgaenge/********, it returns antraege field with only self link without _links parent object. This makes following HAL links imposible.

Sample Response ( Sensitive data is marked with - )
{
    "vorgangsNummer": "-----",
    "externeVorgangsNummer": "-----",
    "erstelltAm": "-----",
    "letztesEreignis": "-----T-----Z",
    "status": "AKTIV",
    "bankverbindung": {-----    },
    "haushalte": [ -----  ],
    "finanzierungsObjekt": {-----},
    "vorhaben": { -----   },
    "datenKontext": "ECHT_GESCHAEFT",
    "aufbewahrungBis": "-----",
    "_links": {
        "ereignisse": {
            "href": "https://baufismart.api.europace.de/v1/ereignisse?vorgangsNummer=-----"
        },
        "self": {
            "href": "https://baufismart.api.europace.de/v2/vorgaenge/-----"
        }
    },
    "antraege": [
        {
            "self": {
                "href": "https://api.europace2.de/v2/vorgaenge/-----/antraege/1/1"
            }
        }
    ],
    "kundenBetreuer": {-----},
    "vorgangsBearbeiter": {-----}
}

**Comment by caspii** [comment]
Hi @mustafakara 

Not all Vorgänge (=Cases) have Anträge (=Applications). Can you give a Vorgangsnummer where you see this problem? A Vorgangsnummer is not sensitive information.

**Comment by mustafakara** [comment]
Hello @caspii,

Sample case numbers for this problem UW53AA(has one application) and XX5VS5 (has two applications)

Thank you very much

**Comment by caspii** [comment]
Hi @mustafakara,

Thanks for the info. I've just discussed it with a developer and you are correct: the current structure does not conform to the standard.
