### ISSUE TITLE
Reporting Feld "bearbeitungsGebuehrKundenBetreuer" fehlt in der API

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#47]
Problem:
Reporting Feld "bearbeitungsGebuehrKundenBetreuer" fehlt in der API.

Lösungsidee:
Im Bitex Model am Darlehen betseht das Feld "vertriebsBearbeitungsGebuehr" schon. API Model erweitern + Mapper

**Comment by KoneFuzius** [comment]
wurde mit der Modelversion 146 entfernt. daher nicht mehr notwendig.

**Comment by a-dudko** [comment]
@KoneFuzius heisst das, dass bearbeitungsGebuehrKundenBetreuer für Report nicht mehr gultig ist?
