### ISSUE TITLE
gemerkte Angebote am Vorgang liefern

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#51]
Kontext:
https://trello.com/c/O8gQoWaN/50-gemerkte-angebote-am-vorgang-liefern-qp-dr-klein

**Comment by ic-hv** [comment]
Wäre auch möglich die **Annahmefristen** der einzelnen Angebote mit auszuspielen, die sind in `gemerkteAngeboteExperimentell / <Angebot> Array` bisher leider noch nicht zu finden.
