### ISSUE TITLE
In der Dokumentation fehlen Beispiele wie Timestamps formatiert werden sollten --> Schlechte DX!

### ISSUE THREAD

**Issue by caspii** [europace/baufismart-vorgaenge-api#57]
Es geht um [diese Dou](https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/baufismart-vorgaenge-api/master/dokumentation/index.html#_getvorgaenge). Das ist ein Problem. weil der Dev nicht weiß, welches Format er hier angeben muss

![image](https://user-images.githubusercontent.com/3215971/77649778-abeeec80-6f6a-11ea-9596-5585f82ace7e.png)

Hängt evtl. auch mit #44 zusammen

**Comment by KoneFuzius** [comment]
PR ist erstellt und wurde gereviewed. Wird die Tage final
