### ISSUE TITLE
Via /v2/vorgaenge/{vorgangsNummer}/finanzierungsvorschlaege: Fehlender Darlehens-Typ und Tilgungs-Informationen

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-vorgaenge-api#58]

**Comment by ic-hv** [comment]
Es wäre auch sehr cool, wenn das **Annahmedatum** mit ausgegeben werden könnte, insofern ein Angebot angenommen wurde.

**Comment by ic-hv** [comment]
Via https://baufismart.api.europace.de/v2/vorgaenge/{ID}/finanzierungsvorschlaege wird die Annahmefrist mit ausgegeben, aber leider nicht via 
https://baufismart.api.europace.de/v2/vorgaenge/{ID}/gemerkteAngebot
obwohl es ja eigentlich hier relavnt wäre ... finanzierungsvorschlaege enthält ja eh' nur die Angebote die bereits angenommen wurden, d.h. hier spielt die Annahmefrist ja eigentlich eh' nur noch einen untergeordnetete Rolle ... bei gemerkteAngebote da wäre die Annahmefrist wichtig zu wissen ...

**Comment by ic-hv** [comment]
Nach Rücksprache mit dem Kunden wären es wohl auch ok, nur die Daten Vorschläge zu verwenden, die via **/v2/vorgaenge/{vorgangsNummer}/finanzierungsvorschlaege** ausgeliefert werden - allerdings kommen da ja nur Mock-Daten :( wann ist hier mit **Echtdaten** zu rechnen? Kann ja eigentlich nicht so lang dauern sein, da das Ganze via gemerkteAngebote ja schon reibungslos läuft ...

**Comment by KoneFuzius** [comment]
Ich werde die Anfrage morgen früh im Team disktutieren und vorab mal eine Einschätzung machen, wieviel Aufwand das ist. Gebe dir morgen hierzu Feedback.

**Comment by ic-hv** [comment]
Ok, ich habe gesehen, das ein neues Release herausgegeben wurde (https://github.com/europace/baufismart-vorgaenge-api/releases/tag/2.16) - allerdings kriege ich nun zwar keine Mock-Daten mehr zurückgeliefert, sondern stattdessen ein leeres JSON-Array ohne Inhalt, also weder ein finanzierungfsvorschlaege-Sektion oder die obligatorische links-Sektion oder ähnliches ... der Request wird aber mit einem 200-er HTTP-Status beantwortet - aber eben mit einem leern JSON-Resultat ...

**Comment by ic-hv** [comment]
Ich habe folgende URL für den Request verwendet:

https://baufismart.api.europace.de/v2/vorgaenge/QD8779/finanzierungsvorschlaege

**Comment by KoneFuzius** [comment]
Hallo,
vergessen zu sagen und zu dokumentieren :( Der Endpunkt funktioniert nur für FinVos, die ab dem 30.5. ausgehändigt wurden. Wir konnten den alten Datenbestand nicht klar zu FinVos mappen.
Sorry für die Unklarheiten.

**Comment by ic-hv** [comment]
Ok, mit frisch ausgehändigten Vorschlägen klappt das Ganze - allerdings fehlen ein paar wichtige Details in den aufgelisteten Darlehen - der **Darlehens-Typ** und die **Tilgungs-Informationen**.

siehe: https://htmlpreview.github.io/?https://raw.githubusercontent.com/europace/baufismart-vorgaenge-api/master/dokumentation/index.html#_darlehen

![typ](https://user-images.githubusercontent.com/26538616/84883893-689baa00-b091-11ea-88d3-7dcbe4c61a22.png)
![tilgung](https://user-images.githubusercontent.com/26538616/84883918-705b4e80-b091-11ea-8f47-8a68cdbbe682.png)

Ohne diese Informationen macht diese API für uns leider keinen Sinn ...

**Comment by KoneFuzius** [comment]
Danke für die Info. Wir besprechen das fachlich und geben euch Feedback

**Comment by ic-hv** [comment]
Sorry, ohne euch stressen zu wollen ... any progress on this?

**Comment by acodingsquirrel** [comment]
Hey ic-hv,
wir sind das Thema noch nicht angegangen.
Wir wissen noch, dass das Thema bei dir einen Mehrwert hebt. Wir schätzen das Thema auch als wichtigen Schritt ein, um unsere Schnittstellenlandschaft auszubauen. Wenn wir dazu kommen die Anpassung anzugehen, melden wir uns bei dir.

**Comment by acodingsquirrel** [comment]
Hallo,

wir haben den den Darlehenstyp und die Tilgungsinformationen in der Vorgänge-API bei ausgehändigten Finanzierungsvorschlägen aufgenommen.
@ic-hv
