### ISSUE TITLE
Quelle für Verkehrswert liefern

### ISSUE THREAD

**Issue by ollio** [europace/baufismart-vorgaenge-api#6]
Wir geben bei den erfassten Daten den Verkehrswert mit aus. Leider ist bei dem Wert nicht ersichtlich, ob dieser eingegeben oder durch einen Anbieter wie vdp ermittelt wurde, gleichwohl wird die Quelle in den Dokumenten mit ausgegeben.

Deshalb soll neben dem Feld Verkehrswert auch noch die Quelle als ENUM-Feld mitgeliefert werden.

** Feldname: verkehrswertQuelle
ENUM-Ausprägungen: 
-EINGABE
-VDP_RESEARCH **

Inside: Es war sehr missverständlich und erforderte einen Analyse herauszufinden, dass der Marktwert in der Schnittstelle Verkehrswert heißt.

**Test-Antrag: DN0891/6/1**

![image](https://user-images.githubusercontent.com/570380/40794739-59011b9a-6500-11e8-929b-7a6ba69569ad.png)

![image](https://user-images.githubusercontent.com/570380/40794755-667d08f6-6500-11e8-9d83-356b3bc6356e.png)

https://trello.com/c/G7xELXRH/51-quelle-f%C3%BCr-verkehrswert-liefern

**Comment by ollio** [comment]
ImmobilieBasisAngabenPresenterImpl::model.setVerkehrswert(marktwert) (179) erweitern

**Comment by ollio** [comment]
@caspii nach Analyse habe ich festgestellt, dass die Info ob der Verkehrswert eingegeben oder von VDP stammt nicht persistiert wird, sondern nur im Browser temporär gespeichert. 
Soll dieses Verhalten in EP2 mit geändert werden?
Was wäre dann der Default Wert?

**Comment by caspii** [comment]
@ollio ich habe gerade mit Mike gesprochen. Dieser Wunsch kam ursprünglich von ihm. Er sagt: kann erstmal geschlossen werden.

Bemerkung am Rande, in der API sollte das Feld nicht `verkehrswert` heissen.

**Comment by ollio** [comment]
https://github.com/europace/baufismart-vorgaenge-api/issues/30
