### ISSUE TITLE
Beim durchleitenden Institut ist der 2. Produktanbieter nicht explizit gekennzeichnet

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#63]
### **Problem**:
Beim Auslesen der Antrags Darlehen und deren Produktanbieter gibt es Fälle, wo man nicht genau weiß, welches Darlehen ist in welchem 'Teilantrag' enthalten. Wir geben nämlich aktuell alle Darlehen in allen Teilanträgen aus :( Nicht wie bei der Antrags API, nur die Darlehen, die sich wirklich in dem jeweiligen Teilantrag beziehen.

**Problembeschreibung an einem Beispiel:**
Bei Finanzierungen mit einem Kfw Darlehen, wobei dieses Darlehen von einem separatem Produktanbieter entschieden wird, werden 2 Anträge erstellt. Einer mit dem Annuitätendarlehen, der andere mit dem KfW. Heißt 3 Produktanbieter, aber nur 2 Teilanträge. Das ist korrekt, aber nun wirds kompliziert.

Aktuell werden in den Anträgen der Vorgänge API, beide Darlehen in jeweils beiden Anträgen zurückgegeben.  das führt schon zu Irritation.  Plus: Der führende (entscheidende) Produktanbieter ist bei beiden Anträgen korrekt. Einmal der des Annus, zum anderen der Dritte, der das KfW Darlehen entscheiden soll. Jedoch ist der Produktanbieter direkt am KfW Darlehen nicht der führende entscheidende Produktanbieter (dritter PB), sondern Kfw. Dadurch ist nicht ersichtlich, dass im zweiten Antrag das KfW vom führenden Entschieden wird.

### Beispiel:

Angebot: 
    - Annu (Sparkasse PB)
    - KfW (Immo PB)

-> Wirklich:

2 Anträge:
    - 1. Antrag - Darlehen: Annu (Sparkasse PB) + führender PB: Sparkasse PB
    - 2. Antrag - Darlehen: KfW (Immo PB) + führender PB: Immo PB

-> Aktuell in der Vorgänge API (Anträge):

2 Anträge:
    - 1. Antrag - Darlehen: 1. Annu (Sparkasse PB), 2.KfW + führender PB: Sparkasse PB
    - 2. Antrag - Darlehen: 1. Annu (Sparkasse PB), 2.KfW + führender PB: Immo PB

### Doing:
Wir müssen in den Anträgen nur die Darlehen ausgeben, die wirklich der führende PB auch entscheidet. 

Beispielfall: B29ASJ/1/2

Internes Ticket: BER-276

**Comment by a-dudko** [comment]
Ich möchte ein bisschen den Grund für unsere Sorge erklären. Eine Kfw kommt immer im gleichen Teilantrag mit dem Hauptdarlehen: sowohl in report.zip als auch in Vorgänge API. Der Unterschied erscheint, wenn für einen Antrag es mehrere Teilanträge gibt. Also sieht Beispiel 1 in Vorgänge API korrekt aus. Beispiel 2 - teilweise (nur 2. Antrag, der einen Teilantrag enthält).

**Beispiel 1** (DL6044)

-> Aktuell in report.zip:

1 Antrag (mit 1 Teilantrag):
1. Antrag 1. Teilantrag - Darlehen: 1. Annu (Sparkasse PB), 2.KfW + führender PB: Sparkasse PB

-> Aktuell in der Vorgänge API (Anträge):

1 Antrag (mit 1 Teilantrag):
1. Antrag 1. Teilantrag - Darlehen: 1. Annu (Sparkasse PB), 2.KfW + führender PB: Sparkasse PB

**Beispiel 2** (ZB8ZG9)

-> Aktuell in report.zip:

2 Anträge (mit 2 und mit 1 Teilantrag):
- Antrag 1. Teilantrag 1. - Darlehen: 1. Annu (DB PB), 2.KfW + führender PB: DB PB
- Antrag 1. Teilantrag 2. - Darlehen: Privat (Hanseatic PB) + führender PB: Hanseatic PB
- Antrag 2. Teilantrag 1. - Darlehen: 1. KfW, 2. Annu (DB PB), 3. Annu (DB Bauspar PB)  + führender PB: DB PB

-> Aktuell in der Vorgänge API (Anträge):

2 Anträge (mit 2 und mit 1 Teilantrag):

- Antrag 1. Teilantrag 1. - Darlehen: 1. Annu (DB PB), 2. KfW, 3. Privat (Hanseatic PB) + führender PB: DB PB
- Antrag 1. Teilantrag 2. - Darlehen: 1. Annu (DB PB), 2. KfW, 3. Privat (Hanseatic PB) + führender PB: Hanseatic PB
- Antrag 1. Teilantrag 1. - Darlehen: 1. KfW, 2. Annu (DB PB), 3. Annu (DB Bauspar PB)  + führender PB: DB PB

**Comment by acodingsquirrel** [comment]
Das Problem ist, das über die API bei einem Teilantrag alle Bausteine des Antrags ausgewiesen werden.
Es ist bei einem KfW Darlehen plus einem weiteren Teilantrag dadurch nicht erkennbar, welche Teilbausteine zum Teilantrag gehören und welche Bausteine zu einem anderen Teilantrag.

Die vorgeschlagene Lösung ist, das wir am Teilantrag nur die Bausteine des Teilantrags ausweisen. Dann findet man unter einem Teilantrag den Hauptdarlehensgeber und das KfW Darlehen.
