### ISSUE TITLE
Annahme Zeitpunkt Unklarheiten

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#64]
### Problem

In der Vorgänge API ist nicht ganz klar was hinter dem Feld "zeitpunktDerAnnahme" steht. Im Reporting haben wir hierzu mehrere Felder und es ist nicht ganz klar, welches dieser Felder das Feld  "zeitpunktDerAnnahme" wiederspiegelt.

**Vorgänge-API:**
- zeitpunktDerAnnahme: Spiegelt den Zeitpunkt der Angebotsanahme durch den Kundenberater wieder (In der Liste klickt der Vertrieb Angebot annehmen).

**Reporting:** 
- angebotAngenommenAmDatum: identisch zur Vorgänge API ("zeitpunktDerAnnahme")
- antragBeantragtAntragstellerAmDatum: Wird gesetzt bei:
      - bei Gegenangebot
      - Bei folgenden Statusänderungen: Wenn Antragsteller Status auf 'Beantragt' und Produktanbieter Status auf 'nicht bearbeitet' gesetzt wird.

### Beispiel: 
ZR14MX 

**Umsetzung:**
Wie belassen es im Reporting so. 
In der Vorgänge API ergänzen wir die API Felddokumentation.

Internes Ticket: BER-275

**Comment by acodingsquirrel** [comment]
Hintergrund: Wie der Status "Annahme Zeitpunkt" gesetzt wird, ist für User nicht verständlich. Deswegen dokumentieren wir die dahinterliegende Logik in der API Beschreibung.

**Comment by a-dudko** [comment]
Eine Richtigstellung: wir antragBeantragtAntragstellerAmDatum in report.zip festegesetzt wird, ist nicht verständlich.
