### ISSUE TITLE
Antragsteller: einkommenNettoMonatlich vs. einkommenNettoJahrlich

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#65]
### Problem:
Im Gegensatz zum Report wird in der  Vorgänge API zum einen "einkommenNettoJaehrlich" und zum anderen "einkommenNettoMonatlich" ausgegeben. Unklar ist wann was zurückgegeben ird.

**Reporting:**
Es wird immer das monatliche Einkommen ausgegeben.

**Vorgänge API:**
Wenn Beschaeftigung “freiberufler” oder “selbstaendiger” ->
  * beschaeftigung.einkommenNettoJaehrlich
  * beschaeftigung.firma
Ansonsten:
  * beschaeftigung.einkommenNettoMonatlich

### Umsetzung:
wir geben in Zukunft auch in der Vorgänge API immer das netto einkommen monatlich mit aus.
Heißt: Feld "einkommenNettoJaehrlich" auf deprecated setzen und das Feld "einkommenNettoMonatlich" immer setzen.

Internes Ticket: BER-273

**Comment by a-dudko** [comment]
Ich glaube, dass Reporting immer einkommenNettoMonatlich enthält. Für Freiberufler ist es einkommenNettoJaehrlich / 12 dann.

**Comment by KoneFuzius** [comment]
Danke für den Hinweis. Ich check da mal im code

**Comment by KoneFuzius** [comment]
wir geben in Zukunft auch in der Vorgänge API immer das netto einkommen mit aus.

**Comment by acodingsquirrel** [comment]
*netto einkommen monatlich
