### ISSUE TITLE
KFW_DARLEHEN : tilgungsFreieAnlaufJahre

### ISSUE THREAD

**Issue by KoneFuzius** [europace/baufismart-vorgaenge-api#67]
### Problem:
Unklarheiten beim Feld "tilgungsFreieAnlaufJahre" in der Vorgänge API. Dieses ist im Report anders benannt.

**Im Report:**
 - kfwTilgungsfreieJahre: Man muss in den ersten Jahren nicht tilgen, was den Vorteil hat, dass die Belastung eine reine Zinsbelastung ist.”

**Vorgänge API:**
- tilgungsfreieAnlaufJahre: Fachlich der gleiche Wert wie im Reporting "kfwTilgungsfreieJahre"

### Doing
Wir kommentieren das Feld mit einer Referenz zum Reporting Feld "kfwTilgungsfreieJahre". Dadurch sollte in der Vorgänge API klar sei, welcher Wert dahinter steckt.

Internes Ticket BER-274

**Comment by acodingsquirrel** [comment]
Wir reden von tilgungsfreien Anlaufjahren und unterscheiden anders als im Reporting nicht mehr zwischen kfw tilgungsfreien Anlaufjahren und tilgungsfreien Anlaufjahren. 
Nach Rücksprache mit Nancy haben wir keinen Grund für eine Unterscheidung gesehen.

**Comment by KoneFuzius** [comment]
behoben
