### ISSUE TITLE
GET /v2/vorgaenge in Verbindung mit aenderungSeit lässt manche Vorgänge unberücksichtigt

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-vorgaenge-api#80]
Hallo allerseits,

folgender Bug(?) ist mir bei einem Echt-Vorgang (und auch noch einigen anderen) aufgefallen.

Die Vorgangsnummer lautet: **WR0ASG**

Der Vorgang wurde am 19.10 angelegt und das letzte Ereignis (Stand heute) ist am: **2020-10-19T16:36:16.637Z**

Wenn ich nun alle Vorgänge abfrage, die sich seit dem spezifizierten Timestamp (-2 Stunden) geändert haben, mittels:

**https://baufismart.api.europace.de/v2/vorgaenge?aenderungSeit=2020-10-19T14%3A36%3A16&limit=100&page=0&datenKontext=ECHT_GESCHAEFT&sort=aufsteigend**

Dann ist dieser Vorgang nicht dabei, auch wenn ich den page-Parameter vergrössere - der Vorgang wird nicht gelistet - und 
damit folglich auch nicht in das CRM des Kunden synchronisiert.

**Comment by KoneFuzius** [comment]
Hallo,

ich nehme mich der Sache an und gebe heute Feedback.

Lg martin

**Comment by ic-hv** [comment]
Danke!

Der API-Client (OAuth) den ich für die Abfrage verwende, ist unter der Partner-ID **BSD88** verknüpft

**Comment by ic-hv** [comment]
Kurzes Update: Ich hatte einen Fehler in meiner Testing-Routine - **mittlerweile wird der Fall mit obigem Aufruf gefunden**. **Allerdings wurde er am 19.10. mit obigem Aufruf nicht gefunden** ...

Da dies in den letzten 10 Tagen Wochen gehäuft passiert, das einige Fälle nicht synchronisert werden, wollte ich mich nur mal erkundigen, wie lange es denn dauern kann, bis ein Fall mit Änderungen dann auch von der Vorgänge-API unter Verwendung des aenderungSeit - Parameters erfasst wird?

**Comment by KoneFuzius** [comment]
Hallo,

Danke für die weiteren Infos. Wir haben dies Problem mit der zeitversetzten Aktualisierung des Suchindex auch an anderen Stellen. Wir haben das Problem  auf unserem Bord und. werden es zeitnah angehen. Wie lange im Worstcase die Aktualisierung dauert kann ich dir leider nicht sagen. Ich nehme an, dass wir an der Stelle bei vielen vielen Änderungen ein Abarbeitungsproblem haben. Wie die Queue und der Subscriber hier konfiguriert ist werde ich mit den Implementierenden Entwickler klären. 

Lg kone

**Comment by ic-hv** [comment]
Ok, danke fürs Feedback - es scheint das sich die Probleme auf unserer Seite nun erledigt haben - es sieht so aus, als ob während des Syncs einiger Fälle eine unbehandelte Exception ausglöst wurde, die den Sync darauffolgender Fälle verhindert hatte.

Derweil, Happy Coding!
