### ISSUE TITLE
https://baufismart.api.europace.de/v2/vorgaenge/*/vorgangsBearbeiter ist down

### ISSUE THREAD

**Issue by ic-hv** [europace/baufismart-vorgaenge-api#91]
Seit heute morgen 10:51 Uhr werden Requests an den Endpunkt abgewiesen mit:
```
{"traceId":"zuul-api-gatewayAxDMm","message":"Service Unavailable","statusMessage":"Service Unavailable","timestamp":"2021-08-16T10:51:05.161","statusCode":503}
```

Mittlerweile wird als Antwort nur noch gesendet: 
```
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

```
Wurde an der API was geändert oder ist dies nur ein temporäres Problem?

Herzliche Grüße,
Heiko Vogel

**Comment by FabianStuehler** [comment]
Hallo Heiko,

wir haben zur Zeit einen incident. Auch die Europace APIs sind davon betroffen: https://status.europace2.de/dashboard/issues/611a27a2386fb307b84f9d7c

Viele Grüße, Fabian
