### ISSUE TITLE
Deeplink zu Vorgang

### ISSUE THREAD

**Issue by D0mc3k** [europace/baufismart-vorgaenge-api#94]
Hallo Europace Team,
über welche API erhalte ich denn den deeplink zu einem Vorgang?
Grüße und Danke im voraus

**Comment by MikeKrueger75** [comment]
@D0mc3k 
du kannst über den Browser einen Vorgang mit dieser URI öffnen: `https://www.europace2.de/vorgang/oeffne/{{vorgangsNummer}}`
Hilft das?

**Comment by D0mc3k** [comment]
Vielen Dank :)
